Rystic/ATLA-restored

- avatar - four nations restored/common/defines.lua
- avatar - four nations restored/common/laws/crown_laws.txt
- avatar - four nations restored/common/laws/demesne_laws.txt
- avatar - four nations restored/common/laws/ze_council_power_laws.txt
- avatar - four nations restored/common/laws/ze_crown_laws.txt
- avatar - four nations restored/common/laws/ze_demesne_laws.txt
- avatar - four nations restored/common/laws/ze_obligation_laws.txt
Fixed all files in the laws folder, except succession laws.
> Merged laws.

- avatar - four nations restored/decisions/mnm_monastic_order_decisions.txt
- avatar - four nations restored/events/ATLA_society_agni_kai.txt
I editted two files to make fix issue #20, mnm_monastic_order_decision.txt and ATLA_society_agni_kai.txt.
The issue arrised from the a "donate_to_charity_cooldown" flag not getting cleared properly. I ended up writing the decsion in such a way that the flag and event MNSAK.3006 are no longer neccessary, this is an easy fix if y'all really want to rely on flags instead.
Now the decision availablity is based on weather the character has the modifier "recently_donated_to_charity" which is set up to expire/ be removed 360 days after it is added.
I also fixed that a random member of the society is suppose to recieve 100 gold from the dontation.
I believe I have fixed all the bugs from issues #20, if y'all have any questions please do not hesitate to ask. I also left a bunch of comments in my …
> Issue: "Air bendering donating to charity doesn't work #20" fix

- avatar - four nations restored/interface/atla_avatars.gfx
No more invisible bender stacks
> WHO'S YOUR DADDY?

- avatar - four nations restored/localisation/000_atla.csv
Changed to a clearer description (I accidentally uploaded the file with my own grammar typos as the first commit)
> Clarified Dragon Trait Desc

- avatar - four nations restored/events/ATLA_bending.txt
- avatar - four nations restored/localisation/000_atla.csv
Changed EVTOPT to EVTDesc and fixed my mistake of changing EVTOPTB to EVTDESC
> Now Fixed Localization

- avatar - four nations restored/common/governments/feudal_governments.txt
- avatar - four nations restored/common/special_troops/00_special_troops.txt
> Fix for broken Bender icon sprites

- avatar - four nations restored/common/cultures/00_cultures.txt
> Ba Sing Se Culture names addition

- avatar - four nations restored/common/governments/feudal_governments.txt
- avatar - four nations restored/common/laws/a_atla_laws.txt
- avatar - four nations restored/decisions/restoration_decisions.txt
- avatar - four nations restored/events/ATLA_imperial.txt
aded de jure things in chin empire so chin empire will be true counterweight for EK
> G R E A T  C H I N  C H O N G + Fire imperial further fixes

- avatar - four nations restored/localisation/000_religions.csv
> Missing Localization Fix

- avatar - four nations restored/common/on_actions/00_on_actions.txt
> Earth King Event Adjustments

- avatar - four nations restored/interface/province.gfx
Fixed air nomad's temple gfx. Also fixed earth's temple and add looted gfx.
> Fix gfx for air nomad's temple

- avatar - four nations restored/common/landed_titles/01_landed_titles.txt
- avatar - four nations restored/decisions/restoration_decisions.txt
- avatar - four nations restored/localisation/000_atla.csv
- avatar - four nations restored/map/adjacencies.csv
> small fixes and changes

- avatar - four nations restored/common/bloodlines/ATLA_bloodlines.txt
- avatar - four nations restored/common/buildings/00_Castle.txt
- avatar - four nations restored/common/landed_titles/special_titles.txt
- avatar - four nations restored/common/modifier_definitions/00_test_bloodline_definitions.txt
- avatar - four nations restored/decisions/TSP_form_title_decisions.txt
- avatar - four nations restored/events/ATLA_bloodline_events.txt
- avatar - four nations restored/events/ATLA_special.txt
one nation bloodline + title and decision (title will need to be looked at)
metalbender founder bloodline
castle building add-ions
> bl addions, building addions

- avatar - four nations restored/common/artifacts/01_ATLA_artifacts.txt
- avatar - four nations restored/common/bloodlines/ATLA_bloodlines.txt
- avatar - four nations restored/decisions/WT_decisions.txt
- avatar - four nations restored/decisions/nomad_decisions.txt
- avatar - four nations restored/events/ATLA_bloodline_events.txt
Kyoshi slayer bloodlines + events to give them
Royal artifacts + kyoshi fans
Artifact:
elders necklace
water tribe ceremonial robes
kyoshi fan
> Kyoshi slayer, artifacts

- avatar - four nations restored/common/bloodlines/ATLA_bloodlines.txt
- avatar - four nations restored/decisions/TSP_form_title_decisions.txt
- avatar - four nations restored/events/ATLA_bloodline_events.txt
New Earthking for new dynastys with a earthkingdom uniter and Bloodline event to assign them
> new bloodline events

- avatar - four nations restored/common/cb_types/03_cb_types_ATLA.txt
- avatar - four nations restored/common/event_modifiers/mandate_modifiers.txt
- avatar - four nations restored/common/landed_titles/special_titles.txt
- avatar - four nations restored/common/offmap_powers/00_offmap_powers.txt
- avatar - four nations restored/common/on_actions/00_on_actions.txt
- avatar - four nations restored/common/societies/01_societies.txt
- avatar - four nations restored/decisions/ATLA_offmapek_decision.txt
- avatar - four nations restored/events/ATLA.txt
- avatar - four nations restored/events/ATLAEKstory.txt
- avatar - four nations restored/events/ATLA_early_history.txt
- avatar - four nations restored/events/ATLA_earthking.txt
- avatar - four nations restored/events/ATLA_mandate.txt
- avatar - four nations restored/events/ATLA_rc.txt
- avatar - four nations restored/history/titles/e_three_rings.txt
- avatar - four nations restored/history/titles/e_yellow_turbans.txt
- avatar - four nations restored/interface/atla_2.gfx
- avatar - four nations restored/localisation/ATLA_calendar.csv
- avatar - four nations restored/localisation/ek_laws.csv
Only Offmap modifs remain *cough* Chris *cough*
PS i hate github
> Nearly Finished EK overhaul

- avatar - four nations restored/common/landed_titles/special_titles.txt
- avatar - four nations restored/common/objectives/00_JD_ambitions.txt
- avatar - four nations restored/common/scripted_effects/01_scripted_effects_duels.txt
- avatar - four nations restored/common/scripted_score_values/00_scripted_score_values.txt
- avatar - four nations restored/common/scripted_triggers/00_scripted_triggers.txt
- avatar - four nations restored/decisions/TSP_form_title_decisions.txt
- avatar - four nations restored/decisions/mnm_monastic_order_decisions.txt
- avatar - four nations restored/decisions/pirate_decisions.txt
- avatar - four nations restored/decisions/way_of_life_decisions.txt
- avatar - four nations restored/events/ATLA_bending.txt
- avatar - four nations restored/events/ATLA_misc_society_events.txt
- avatar - four nations restored/events/job_offmap.txt
- avatar - four nations restored/events/pirate_events.txt
- avatar - four nations restored/events/religious_events.txt
- avatar - four nations restored/events/rip_flavor_events.txt
- avatar - four nations restored/events/wol_lover_events.txt
- avatar - four nations restored/interface/portrait_properties/00_portrait_properties.txt
- avatar - four nations restored/localisation/customizable_localisation/00_customizable_localisation.txt
> Fix broken triggers

- avatar - four nations restored/localisation/000_atla_custom_titles.csv
- avatar - four nations restored/localisation/00_ATLA_new_title_prefixes.csv
Lit 420 360 no scop Mlg
Fuck github i hate
> Dankest new titles

- avatar - four nations restored/events/ATLA_EKstory.txt
- avatar - four nations restored/events/ATLA_mandate.txt
- avatar - four nations restored/interface/offmapek.gui
- avatar - four nations restored/localisation/ATLA_ek_mandate.csv
> Finished Mandate events with event Descs + offmap_ek gui

- avatar - four nations restored/history/characters/omashu_characters.txt
- avatar - four nations restored/history/titles/c_omashu.txt
- avatar - four nations restored/history/titles/k_omashu.txt
-Fixed Quan-Tou "The One Man Army"'s Death death and his successor's inheritance.
> Quan-Tou Death Date fix

- avatar - four nations restored/common/event_modifiers/mandate_modifiers.txt
- avatar - four nations restored/common/on_actions/00_on_actions.txt
- avatar - four nations restored/common/traits/06_atla_traits.txt
- avatar - four nations restored/decisions/ATLA_offmapek_decision.txt
- avatar - four nations restored/events/ATLA_EKstory.txt
- avatar - four nations restored/events/ATLA_mandate.txt
- avatar - four nations restored/events/ATLA_rc.txt
After two months in development i hope it will be worth a wait.
> Finished Code of EK overhaul

- avatar - four nations restored/common/buildings/flavor_buildings.txt
- avatar - four nations restored/common/landed_titles/ATLA_ek_landed_titles.txt
- avatar - four nations restored/common/modifier_definitions/00_modifier_definitions.txt
- avatar - four nations restored/history/characters/NE_Characters.txt
- avatar - four nations restored/localisation/000_atla_opinion.csv
- avatar - four nations restored/localisation/flavor_buildings.csv
-Added 26 Brand New Flavor buildings peppered around the map! Go Find them!
-Some examples: Northern Chin Memorial, Shaodong Scouting Corps, Mt. Wu Temple
-Minor LOC additions
-Changed the capital of The Kingdom and Empire of Xishan to Hejiagou.
> Special Buildings Update + Minor LOC additions

- avatar - four nations restored/history/titles/e_earth_kingdom.txt
- avatar - four nations restored/localisation/000_new_imperialism.csv
- avatar - four nations restored/localisation/flavor_buildings.csv
-Deactivated e_earth_kingdom so the Earth Kingdom is no longer under a Shogunate
-Gave Localization to the decision to form the Empire Tier Earth Kingdom
-Fixed Avatar Jin Statue in Yanbian not having proper localization if tribal
> Earth Kingdom Fix + decision LOC fix + Flavor building LOC fix

- avatar - four nations restored/events/ATLA_society_sand.txt
> really tiny fix

- avatar - four nations restored/common/dynasties/00_dynasties.txt
- avatar - four nations restored/history/characters/FN_Characters.txt
- avatar - four nations restored/history/titles/c_crescent_island.txt
- avatar - four nations restored/history/titles/d_fire_sages.txt
- avatar - four nations restored/localisation/ATLA_nicknames.csv
-Fire Sages TItle History Revamped!
> Fire Sages Title History Update! 500th pull!

- avatar - four nations restored/localisation/000_fix.csv
- avatar - four nations restored/localisation/ALTA_artifacts.csv
- avatar - four nations restored/localisation/ALTA_tradeposts.csv
Added in a few missing artifacts such as Chins Crown and Kyoshis fans.
Added some tradepost building descriptions. I left them blank for the most part.
> Artifacts Separated and Trade Route building descriptions

- avatar - four nations restored/localisation/ATLA_core.csv
- avatar - four nations restored/localisation/ATLA_trade_routes.csv
-Changed build trade post trigger loc for better understanding of where the player can build trade posts
-Moved all remaining trade route loc out of ATLA_core.csv and into ATLA_trade_routes.csv
> Bug fix branch

- avatar - four nations restored/common/scripted_effects/09_atla_scripted_effects.txt
- avatar - four nations restored/decisions/dynasty_decisions.txt
- avatar - four nations restored/events/ATLA.txt
You can make a child into a Firesage now. I should probably add a clause so that they need to be a frebender but w/o
Woolooloo now works correctly.
> Make your children into Fire Sages and Enforce Doctorine

- avatar - four nations restored/history/characters/atla_characters.txt
- updated/fixed some minor traits for Aang's and the Beifong families (I forgot Avatar descendant traits before, whoops)
> Minor Charcter history/trait update

- avatar - four nations restored/events/ATLA_imperial.txt
Added NOR statement in first event trigger
> Imperialism Hot Fix

- avatar - four nations restored/events/ATLA_avatar_fire_sages.txt
happened due to the fact that the avatar has a title, characters with a title cannot be moved with move_character command
proof:
> fixed the error

- avatar - four nations restored/history/characters/Si_Wong_characters.txt
i would like to punch this bird but i promised to bring him back in some capacity, i may have use for him in the near future
> re added silly spirit bird

- avatar - four nations restored/events/ATLA_society_sand.txt
> forgot something

- avatar - four nations restored/common/on_actions/00_on_actions.txt
- avatar - four nations restored/common/trade_routes/06_si_wong_trail.txt
- avatar - four nations restored/decisions/ATLA_sand_sailer_society_decisions.txt
- avatar - four nations restored/events/ATLA.txt
- avatar - four nations restored/events/ATLA_random_events.txt
- avatar - four nations restored/events/ATLA_sand.txt
- avatar - four nations restored/events/ATLA_society_sand.txt
- avatar - four nations restored/localisation/ATLA_misc_loc.csv
- avatar - four nations restored/localisation/ATLA_sand_sailer_society.csv
9:00 AM- Wake up
9:05 AM- Eat breakfast
9:30 AM- Enter bathroom
10:00 AM- Look into the mirror and repeat to my myself, "You're going to FIX these bugs, and you're going to FIX them TODAY."
11:47 PM- Become aware of the lateness of the hour
12:00 PM- Go to bed
> fixed some errors that would show up in error.log

- avatar - four nations restored/common/buildings/00_hospital.txt
- avatar - four nations restored/common/buildings/00_unique_troop_buildings.txt
deleted and changed not working things in hospital and added a little fix to castle
> Minor change in factory

- avatar - four nations restored/decisions/ATLA_avatar_decisions.txt
- avatar - four nations restored/history/characters/atla_characters.txt
- avatar - four nations restored/localisation/ATLA_new_avatar_general.csv
Unlanded avatars can travel around the world now
> Quickfix move avatar decision

- avatar - four nations restored/common/traits/06_atla_traits.txt
- avatar - four nations restored/decisions/ATLA_sand_sailer_society_decisions.txt
- avatar - four nations restored/events/ATLA_sand.txt
- avatar - four nations restored/events/ATLA_society_sand.txt
- avatar - four nations restored/localisation/ATLA_sand_sailer_society.csv
-made rewards from sand sailer missions and power decisions less overpowered
-made "become sand sailor legend" much more expensive
-more misc variable changes
-Gauntlet power decision event description bug squashed, decision reenabled!
-Domaxs' New Year Resolution: Contribute more
> Return of the Mack

- avatar - four nations restored/common/artifacts/01_ATLA_artifacts.txt
because the earth king traits are wonky (thanks @FalteringSpin)!
> quick fix for earth king crown

- avatar - four nations restored/decisions/ATLA_sand_sailer_society_decisions.txt
"allow" in title decisions scopes to a title, so you need to use FROM (it is a character scope) to use character-scoped conditions
> fix sandsailer fervor decision

- avatar - four nations restored/events/ATLA_mandate.txt
> Fix mandate pictures

- avatar - four nations restored/common/scripted_effects/10_atla_new_avatar_engine_scripted_effects.txt
- avatar - four nations restored/common/scripted_triggers/10_atla_new_avatar_engine_scripted_triggers.txt
- avatar - four nations restored/events/ATLA_avatar_fire_sages.txt
- avatar - four nations restored/events/ATLA_avatar_journey.txt
- avatar - four nations restored/events/chin_events.txt
- avatar - four nations restored/history/characters/atla_characters.txt
- avatar - four nations restored/localisation/customizable_localisation/00_customizable_localisation.txt
* formatted 00_customizable_localisation file
* moved find_fire_lord_effect from a custom trigger
* renamed find_fire_lord effect to find_firelord
* also added a mean time to happen to CHN.1 event
> Fix 00 customizable localisation

- avatar - four nations restored/common/on_actions/00_on_actions.txt
- avatar - four nations restored/common/societies/tea_society.txt
- avatar - four nations restored/decisions/air_nomad_decisions.txt
- avatar - four nations restored/events/AGOT_customizer_houses_events.txt
- avatar - four nations restored/events/ATLA.txt
- avatar - four nations restored/events/ATLA_air_nomad_events.txt
- avatar - four nations restored/events/ATLA_avatar_journey.txt
- avatar - four nations restored/events/ATLA_avatar_system.txt
- avatar - four nations restored/events/ATLA_bending.txt
- avatar - four nations restored/events/adventurers_negotiation.txt
- avatar - four nations restored/events/airbender.txt
- avatar - four nations restored/events/ambition_events.txt
- avatar - four nations restored/localisation/000_atla.csv
- avatar - four nations restored/localisation/ATLA_air_nomad_events.csv
* added a lot of "!nevercalled" marks
* commented out a lot of nevercalled events
* commented events about airbender childbirth
* probably fixed "already in society" bug
> Fix events

- avatar - four nations restored/README.md
- avatar - four nations restored/common/artifacts/01_ATLA_artifacts.txt
- avatar - four nations restored/events/ambition_events.txt
Commit #599 introduced a new system of assignment marking (todos in the code), question marking, and a tagging system.
During the development of a mod, you don't always have time to do what you want to do right here and now.
That's why sometimes we need special comments.
If you are developing with VSCode, then you should install an extension called [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments)
This extension Improves your code commenting by annotating some special words or marks with colors.
* <span style="color:#FF8C00"># todo:</span><span style="color:white">\<text\></span>- what must be done someday
* <span style="color:#3498DB"># ?question:</span><span style="color:white">\<text\></span> - some question to discuss with the team
* …
> Add README with info about Special Comments

- avatar - four nations restored/common/traits/06_atla_traits.txt
- avatar - four nations restored/decisions/imperialism_decisions.txt
- avatar - four nations restored/events/ATLA_society_agni_kai.txt
- avatar - four nations restored/history/characters/atla_characters.txt
- avatar - four nations restored/history/titles/c_gaoqing.txt
- avatar - four nations restored/interface/ATLA_traits.gfx
- avatar - four nations restored/localisation/000_atla_bloodlines.csv
- avatar - four nations restored/localisation/00_ATLA_new_title_prefixes.csv
- avatar - four nations restored/localisation/ATLA_traits.csv
Finished a incomplete trait
Removed incomplete decision
Fixed ATLA history
Added Missing Loc
> ATLA Fixes

- avatar - four nations restored/decisions/ALTA_misc_decisions.txt
- avatar - four nations restored/decisions/lifestyle_decisions.txt
- avatar - four nations restored/decisions/mnm_monastic_order_decisions.txt
- avatar - four nations restored/events/ATLA_bending.txt
- avatar - four nations restored/events/ATLA_society_agni_kai.txt
- avatar - four nations restored/history/characters/atla_characters.txt
- avatar - four nations restored/localisation/000_atla.csv
Added decision to see Legendary and Master Benders
Tweaked AI weights for Spiritual Journey and Teach Airbending decisions 
Tweaked modifiers for children learning and improving their bending abilities 
Added ability to become a Legendary through the White Lotus society 
Fixed a bug where the Agni Kai society would assign a mission before reaching the relevant rank 
Tweaked health values for canon characters
> Misc Update
